[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Open Science Data Repository Tutorial"
authors = [{name = "Richard Barker", email = "richard.barker@nasa.gov"}]
dynamic = ["version", "description"]
