[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OSDR tutorial"
authors = [{name = "Richard", email = "richard.barker@NASA.gov"}]
dynamic = ["version", "description"]
